name: Run Script and Update Results

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs at 8:00 AM UTC daily

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements

      - name: Run script
        run: python script.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push if changes
        run: |
          git add results.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update results" && git push)